language: php

php:
  - 5.6
  - 5.5
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly
  fast_finish: true

install:
  - composer install

script: phpunit
notifications: { email: false }
after_success:
  - php src/scripts/SplitSubTree.php
