language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly
  fast_finish: true

install:
  - composer install

script: phpunit --testdox --boot=vendor/autoload.php tests/
notifications: { email: false }
